/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.CardLayout;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;

/**
 *
 * @author ASUSTek
 */
public class PilihGambarButtonFullScreen extends javax.swing.JFrame {

    /**
     * Creates new form PilihGambarButton
     */
    public PilihGambarButtonFullScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagePanel = new javax.swing.JPanel();
        lblPdi = new javax.swing.JLabel();
        lblDemokrat = new javax.swing.JLabel();
        lblGolkar = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        btnPdi = new javax.swing.JButton();
        btnDeomkrat = new javax.swing.JButton();
        btnGolkar = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        imagePanel.setLayout(new java.awt.CardLayout());

        lblPdi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPdi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pdi.jpg"))); // NOI18N
        imagePanel.add(lblPdi, "0");

        lblDemokrat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDemokrat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/demokrat.png"))); // NOI18N
        imagePanel.add(lblDemokrat, "1");

        lblGolkar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGolkar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/golkar.png"))); // NOI18N
        imagePanel.add(lblGolkar, "2");

        getContentPane().add(imagePanel, java.awt.BorderLayout.CENTER);

        btnPdi.setText("Partai 1");
        btnPdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPdiActionPerformed(evt);
            }
        });
        buttonPanel.add(btnPdi);

        btnDeomkrat.setText("Partai 2");
        btnDeomkrat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeomkratActionPerformed(evt);
            }
        });
        buttonPanel.add(btnDeomkrat);

        btnGolkar.setText("Partai 3");
        btnGolkar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGolkarActionPerformed(evt);
            }
        });
        buttonPanel.add(btnGolkar);

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        buttonPanel.add(btnExit);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPdiActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) (imagePanel.getLayout());
        cl.show(imagePanel, "0");
    }//GEN-LAST:event_btnPdiActionPerformed

    private void btnDeomkratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeomkratActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) (imagePanel.getLayout());
        cl.show(imagePanel, "1");
    }//GEN-LAST:event_btnDeomkratActionPerformed

    private void btnGolkarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGolkarActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) (imagePanel.getLayout());
        cl.show(imagePanel, "2");
    }//GEN-LAST:event_btnGolkarActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButtonFullScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButtonFullScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButtonFullScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButtonFullScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PilihGambarButtonFullScreen fullFrame = new PilihGambarButtonFullScreen();
                
                GraphicsDevice device =
                        GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
                device.setFullScreenWindow(fullFrame);
                
                fullFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeomkrat;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnGolkar;
    private javax.swing.JButton btnPdi;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JLabel lblDemokrat;
    private javax.swing.JLabel lblGolkar;
    private javax.swing.JLabel lblPdi;
    // End of variables declaration//GEN-END:variables
}
